// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_rpc_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_rpc_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3013000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3013000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_rpc_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_rpc_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_rpc_2eproto;
namespace lcy {
namespace rpc {
class Message;
class MessageDefaultTypeInternal;
extern MessageDefaultTypeInternal _Message_default_instance_;
class Request;
class RequestDefaultTypeInternal;
extern RequestDefaultTypeInternal _Request_default_instance_;
class Response;
class ResponseDefaultTypeInternal;
extern ResponseDefaultTypeInternal _Response_default_instance_;
}  // namespace rpc
}  // namespace lcy
PROTOBUF_NAMESPACE_OPEN
template<> ::lcy::rpc::Message* Arena::CreateMaybeMessage<::lcy::rpc::Message>(Arena*);
template<> ::lcy::rpc::Request* Arena::CreateMaybeMessage<::lcy::rpc::Request>(Arena*);
template<> ::lcy::rpc::Response* Arena::CreateMaybeMessage<::lcy::rpc::Response>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace lcy {
namespace rpc {

enum type : int {
  request = 0,
  response = 1,
  type_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  type_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool type_IsValid(int value);
constexpr type type_MIN = request;
constexpr type type_MAX = response;
constexpr int type_ARRAYSIZE = type_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* type_descriptor();
template<typename T>
inline const std::string& type_Name(T enum_t_value) {
  static_assert(::std::is_same<T, type>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function type_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    type_descriptor(), enum_t_value);
}
inline bool type_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, type* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<type>(
    type_descriptor(), name, value);
}
enum err : int {
  SUCCESS = 0,
  NO_SERVICE = 1,
  NO_METHOD = 2,
  INVALID_REQUEST = 3,
  NOT_SUPPORT = 4,
  err_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  err_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool err_IsValid(int value);
constexpr err err_MIN = SUCCESS;
constexpr err err_MAX = NOT_SUPPORT;
constexpr int err_ARRAYSIZE = err_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* err_descriptor();
template<typename T>
inline const std::string& err_Name(T enum_t_value) {
  static_assert(::std::is_same<T, err>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function err_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    err_descriptor(), enum_t_value);
}
inline bool err_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, err* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<err>(
    err_descriptor(), name, value);
}
// ===================================================================

class Request PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:lcy.rpc.Request) */ {
 public:
  inline Request() : Request(nullptr) {}
  virtual ~Request();

  Request(const Request& from);
  Request(Request&& from) noexcept
    : Request() {
    *this = ::std::move(from);
  }

  inline Request& operator=(const Request& from) {
    CopyFrom(from);
    return *this;
  }
  inline Request& operator=(Request&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Request& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Request* internal_default_instance() {
    return reinterpret_cast<const Request*>(
               &_Request_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Request& a, Request& b) {
    a.Swap(&b);
  }
  inline void Swap(Request* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Request* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Request* New() const final {
    return CreateMaybeMessage<Request>(nullptr);
  }

  Request* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Request>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Request& from);
  void MergeFrom(const Request& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Request* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "lcy.rpc.Request";
  }
  protected:
  explicit Request(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_rpc_2eproto);
    return ::descriptor_table_rpc_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kServiceNameFieldNumber = 1,
    kServiceMethodFieldNumber = 2,
    kArgumentsFieldNumber = 3,
  };
  // string service_name = 1;
  void clear_service_name();
  const std::string& service_name() const;
  void set_service_name(const std::string& value);
  void set_service_name(std::string&& value);
  void set_service_name(const char* value);
  void set_service_name(const char* value, size_t size);
  std::string* mutable_service_name();
  std::string* release_service_name();
  void set_allocated_service_name(std::string* service_name);
  private:
  const std::string& _internal_service_name() const;
  void _internal_set_service_name(const std::string& value);
  std::string* _internal_mutable_service_name();
  public:

  // string service_method = 2;
  void clear_service_method();
  const std::string& service_method() const;
  void set_service_method(const std::string& value);
  void set_service_method(std::string&& value);
  void set_service_method(const char* value);
  void set_service_method(const char* value, size_t size);
  std::string* mutable_service_method();
  std::string* release_service_method();
  void set_allocated_service_method(std::string* service_method);
  private:
  const std::string& _internal_service_method() const;
  void _internal_set_service_method(const std::string& value);
  std::string* _internal_mutable_service_method();
  public:

  // bytes arguments = 3;
  void clear_arguments();
  const std::string& arguments() const;
  void set_arguments(const std::string& value);
  void set_arguments(std::string&& value);
  void set_arguments(const char* value);
  void set_arguments(const void* value, size_t size);
  std::string* mutable_arguments();
  std::string* release_arguments();
  void set_allocated_arguments(std::string* arguments);
  private:
  const std::string& _internal_arguments() const;
  void _internal_set_arguments(const std::string& value);
  std::string* _internal_mutable_arguments();
  public:

  // @@protoc_insertion_point(class_scope:lcy.rpc.Request)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr service_name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr service_method_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr arguments_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_rpc_2eproto;
};
// -------------------------------------------------------------------

class Response PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:lcy.rpc.Response) */ {
 public:
  inline Response() : Response(nullptr) {}
  virtual ~Response();

  Response(const Response& from);
  Response(Response&& from) noexcept
    : Response() {
    *this = ::std::move(from);
  }

  inline Response& operator=(const Response& from) {
    CopyFrom(from);
    return *this;
  }
  inline Response& operator=(Response&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Response& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Response* internal_default_instance() {
    return reinterpret_cast<const Response*>(
               &_Response_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Response& a, Response& b) {
    a.Swap(&b);
  }
  inline void Swap(Response* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Response* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Response* New() const final {
    return CreateMaybeMessage<Response>(nullptr);
  }

  Response* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Response>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Response& from);
  void MergeFrom(const Response& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Response* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "lcy.rpc.Response";
  }
  protected:
  explicit Response(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_rpc_2eproto);
    return ::descriptor_table_rpc_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kArgumentsFieldNumber = 2,
    kErrcodeFieldNumber = 1,
  };
  // bytes arguments = 2;
  void clear_arguments();
  const std::string& arguments() const;
  void set_arguments(const std::string& value);
  void set_arguments(std::string&& value);
  void set_arguments(const char* value);
  void set_arguments(const void* value, size_t size);
  std::string* mutable_arguments();
  std::string* release_arguments();
  void set_allocated_arguments(std::string* arguments);
  private:
  const std::string& _internal_arguments() const;
  void _internal_set_arguments(const std::string& value);
  std::string* _internal_mutable_arguments();
  public:

  // .lcy.rpc.err errcode = 1;
  void clear_errcode();
  ::lcy::rpc::err errcode() const;
  void set_errcode(::lcy::rpc::err value);
  private:
  ::lcy::rpc::err _internal_errcode() const;
  void _internal_set_errcode(::lcy::rpc::err value);
  public:

  // @@protoc_insertion_point(class_scope:lcy.rpc.Response)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr arguments_;
  int errcode_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_rpc_2eproto;
};
// -------------------------------------------------------------------

class Message PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:lcy.rpc.Message) */ {
 public:
  inline Message() : Message(nullptr) {}
  virtual ~Message();

  Message(const Message& from);
  Message(Message&& from) noexcept
    : Message() {
    *this = ::std::move(from);
  }

  inline Message& operator=(const Message& from) {
    CopyFrom(from);
    return *this;
  }
  inline Message& operator=(Message&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Message& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Message* internal_default_instance() {
    return reinterpret_cast<const Message*>(
               &_Message_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Message& a, Message& b) {
    a.Swap(&b);
  }
  inline void Swap(Message* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Message* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Message* New() const final {
    return CreateMaybeMessage<Message>(nullptr);
  }

  Message* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Message>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Message& from);
  void MergeFrom(const Message& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Message* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "lcy.rpc.Message";
  }
  protected:
  explicit Message(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_rpc_2eproto);
    return ::descriptor_table_rpc_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRequestFieldNumber = 3,
    kResponseFieldNumber = 4,
    kIdFieldNumber = 1,
    kTpFieldNumber = 2,
  };
  // .lcy.rpc.Request request = 3;
  bool has_request() const;
  private:
  bool _internal_has_request() const;
  public:
  void clear_request();
  const ::lcy::rpc::Request& request() const;
  ::lcy::rpc::Request* release_request();
  ::lcy::rpc::Request* mutable_request();
  void set_allocated_request(::lcy::rpc::Request* request);
  private:
  const ::lcy::rpc::Request& _internal_request() const;
  ::lcy::rpc::Request* _internal_mutable_request();
  public:
  void unsafe_arena_set_allocated_request(
      ::lcy::rpc::Request* request);
  ::lcy::rpc::Request* unsafe_arena_release_request();

  // .lcy.rpc.Response response = 4;
  bool has_response() const;
  private:
  bool _internal_has_response() const;
  public:
  void clear_response();
  const ::lcy::rpc::Response& response() const;
  ::lcy::rpc::Response* release_response();
  ::lcy::rpc::Response* mutable_response();
  void set_allocated_response(::lcy::rpc::Response* response);
  private:
  const ::lcy::rpc::Response& _internal_response() const;
  ::lcy::rpc::Response* _internal_mutable_response();
  public:
  void unsafe_arena_set_allocated_response(
      ::lcy::rpc::Response* response);
  ::lcy::rpc::Response* unsafe_arena_release_response();

  // uint64 id = 1;
  void clear_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 id() const;
  void set_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_id() const;
  void _internal_set_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // .lcy.rpc.type tp = 2;
  void clear_tp();
  ::lcy::rpc::type tp() const;
  void set_tp(::lcy::rpc::type value);
  private:
  ::lcy::rpc::type _internal_tp() const;
  void _internal_set_tp(::lcy::rpc::type value);
  public:

  // @@protoc_insertion_point(class_scope:lcy.rpc.Message)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::lcy::rpc::Request* request_;
  ::lcy::rpc::Response* response_;
  ::PROTOBUF_NAMESPACE_ID::uint64 id_;
  int tp_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_rpc_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Request

// string service_name = 1;
inline void Request::clear_service_name() {
  service_name_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& Request::service_name() const {
  // @@protoc_insertion_point(field_get:lcy.rpc.Request.service_name)
  return _internal_service_name();
}
inline void Request::set_service_name(const std::string& value) {
  _internal_set_service_name(value);
  // @@protoc_insertion_point(field_set:lcy.rpc.Request.service_name)
}
inline std::string* Request::mutable_service_name() {
  // @@protoc_insertion_point(field_mutable:lcy.rpc.Request.service_name)
  return _internal_mutable_service_name();
}
inline const std::string& Request::_internal_service_name() const {
  return service_name_.Get();
}
inline void Request::_internal_set_service_name(const std::string& value) {
  
  service_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void Request::set_service_name(std::string&& value) {
  
  service_name_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:lcy.rpc.Request.service_name)
}
inline void Request::set_service_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  service_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:lcy.rpc.Request.service_name)
}
inline void Request::set_service_name(const char* value,
    size_t size) {
  
  service_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:lcy.rpc.Request.service_name)
}
inline std::string* Request::_internal_mutable_service_name() {
  
  return service_name_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* Request::release_service_name() {
  // @@protoc_insertion_point(field_release:lcy.rpc.Request.service_name)
  return service_name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Request::set_allocated_service_name(std::string* service_name) {
  if (service_name != nullptr) {
    
  } else {
    
  }
  service_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), service_name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:lcy.rpc.Request.service_name)
}

// string service_method = 2;
inline void Request::clear_service_method() {
  service_method_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& Request::service_method() const {
  // @@protoc_insertion_point(field_get:lcy.rpc.Request.service_method)
  return _internal_service_method();
}
inline void Request::set_service_method(const std::string& value) {
  _internal_set_service_method(value);
  // @@protoc_insertion_point(field_set:lcy.rpc.Request.service_method)
}
inline std::string* Request::mutable_service_method() {
  // @@protoc_insertion_point(field_mutable:lcy.rpc.Request.service_method)
  return _internal_mutable_service_method();
}
inline const std::string& Request::_internal_service_method() const {
  return service_method_.Get();
}
inline void Request::_internal_set_service_method(const std::string& value) {
  
  service_method_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void Request::set_service_method(std::string&& value) {
  
  service_method_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:lcy.rpc.Request.service_method)
}
inline void Request::set_service_method(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  service_method_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:lcy.rpc.Request.service_method)
}
inline void Request::set_service_method(const char* value,
    size_t size) {
  
  service_method_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:lcy.rpc.Request.service_method)
}
inline std::string* Request::_internal_mutable_service_method() {
  
  return service_method_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* Request::release_service_method() {
  // @@protoc_insertion_point(field_release:lcy.rpc.Request.service_method)
  return service_method_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Request::set_allocated_service_method(std::string* service_method) {
  if (service_method != nullptr) {
    
  } else {
    
  }
  service_method_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), service_method,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:lcy.rpc.Request.service_method)
}

// bytes arguments = 3;
inline void Request::clear_arguments() {
  arguments_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& Request::arguments() const {
  // @@protoc_insertion_point(field_get:lcy.rpc.Request.arguments)
  return _internal_arguments();
}
inline void Request::set_arguments(const std::string& value) {
  _internal_set_arguments(value);
  // @@protoc_insertion_point(field_set:lcy.rpc.Request.arguments)
}
inline std::string* Request::mutable_arguments() {
  // @@protoc_insertion_point(field_mutable:lcy.rpc.Request.arguments)
  return _internal_mutable_arguments();
}
inline const std::string& Request::_internal_arguments() const {
  return arguments_.Get();
}
inline void Request::_internal_set_arguments(const std::string& value) {
  
  arguments_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void Request::set_arguments(std::string&& value) {
  
  arguments_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:lcy.rpc.Request.arguments)
}
inline void Request::set_arguments(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  arguments_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:lcy.rpc.Request.arguments)
}
inline void Request::set_arguments(const void* value,
    size_t size) {
  
  arguments_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:lcy.rpc.Request.arguments)
}
inline std::string* Request::_internal_mutable_arguments() {
  
  return arguments_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* Request::release_arguments() {
  // @@protoc_insertion_point(field_release:lcy.rpc.Request.arguments)
  return arguments_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Request::set_allocated_arguments(std::string* arguments) {
  if (arguments != nullptr) {
    
  } else {
    
  }
  arguments_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), arguments,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:lcy.rpc.Request.arguments)
}

// -------------------------------------------------------------------

// Response

// .lcy.rpc.err errcode = 1;
inline void Response::clear_errcode() {
  errcode_ = 0;
}
inline ::lcy::rpc::err Response::_internal_errcode() const {
  return static_cast< ::lcy::rpc::err >(errcode_);
}
inline ::lcy::rpc::err Response::errcode() const {
  // @@protoc_insertion_point(field_get:lcy.rpc.Response.errcode)
  return _internal_errcode();
}
inline void Response::_internal_set_errcode(::lcy::rpc::err value) {
  
  errcode_ = value;
}
inline void Response::set_errcode(::lcy::rpc::err value) {
  _internal_set_errcode(value);
  // @@protoc_insertion_point(field_set:lcy.rpc.Response.errcode)
}

// bytes arguments = 2;
inline void Response::clear_arguments() {
  arguments_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& Response::arguments() const {
  // @@protoc_insertion_point(field_get:lcy.rpc.Response.arguments)
  return _internal_arguments();
}
inline void Response::set_arguments(const std::string& value) {
  _internal_set_arguments(value);
  // @@protoc_insertion_point(field_set:lcy.rpc.Response.arguments)
}
inline std::string* Response::mutable_arguments() {
  // @@protoc_insertion_point(field_mutable:lcy.rpc.Response.arguments)
  return _internal_mutable_arguments();
}
inline const std::string& Response::_internal_arguments() const {
  return arguments_.Get();
}
inline void Response::_internal_set_arguments(const std::string& value) {
  
  arguments_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void Response::set_arguments(std::string&& value) {
  
  arguments_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:lcy.rpc.Response.arguments)
}
inline void Response::set_arguments(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  arguments_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:lcy.rpc.Response.arguments)
}
inline void Response::set_arguments(const void* value,
    size_t size) {
  
  arguments_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:lcy.rpc.Response.arguments)
}
inline std::string* Response::_internal_mutable_arguments() {
  
  return arguments_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* Response::release_arguments() {
  // @@protoc_insertion_point(field_release:lcy.rpc.Response.arguments)
  return arguments_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Response::set_allocated_arguments(std::string* arguments) {
  if (arguments != nullptr) {
    
  } else {
    
  }
  arguments_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), arguments,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:lcy.rpc.Response.arguments)
}

// -------------------------------------------------------------------

// Message

// uint64 id = 1;
inline void Message::clear_id() {
  id_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Message::_internal_id() const {
  return id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Message::id() const {
  // @@protoc_insertion_point(field_get:lcy.rpc.Message.id)
  return _internal_id();
}
inline void Message::_internal_set_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  id_ = value;
}
inline void Message::set_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:lcy.rpc.Message.id)
}

// .lcy.rpc.type tp = 2;
inline void Message::clear_tp() {
  tp_ = 0;
}
inline ::lcy::rpc::type Message::_internal_tp() const {
  return static_cast< ::lcy::rpc::type >(tp_);
}
inline ::lcy::rpc::type Message::tp() const {
  // @@protoc_insertion_point(field_get:lcy.rpc.Message.tp)
  return _internal_tp();
}
inline void Message::_internal_set_tp(::lcy::rpc::type value) {
  
  tp_ = value;
}
inline void Message::set_tp(::lcy::rpc::type value) {
  _internal_set_tp(value);
  // @@protoc_insertion_point(field_set:lcy.rpc.Message.tp)
}

// .lcy.rpc.Request request = 3;
inline bool Message::_internal_has_request() const {
  return this != internal_default_instance() && request_ != nullptr;
}
inline bool Message::has_request() const {
  return _internal_has_request();
}
inline void Message::clear_request() {
  if (GetArena() == nullptr && request_ != nullptr) {
    delete request_;
  }
  request_ = nullptr;
}
inline const ::lcy::rpc::Request& Message::_internal_request() const {
  const ::lcy::rpc::Request* p = request_;
  return p != nullptr ? *p : *reinterpret_cast<const ::lcy::rpc::Request*>(
      &::lcy::rpc::_Request_default_instance_);
}
inline const ::lcy::rpc::Request& Message::request() const {
  // @@protoc_insertion_point(field_get:lcy.rpc.Message.request)
  return _internal_request();
}
inline void Message::unsafe_arena_set_allocated_request(
    ::lcy::rpc::Request* request) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(request_);
  }
  request_ = request;
  if (request) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:lcy.rpc.Message.request)
}
inline ::lcy::rpc::Request* Message::release_request() {
  
  ::lcy::rpc::Request* temp = request_;
  request_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::lcy::rpc::Request* Message::unsafe_arena_release_request() {
  // @@protoc_insertion_point(field_release:lcy.rpc.Message.request)
  
  ::lcy::rpc::Request* temp = request_;
  request_ = nullptr;
  return temp;
}
inline ::lcy::rpc::Request* Message::_internal_mutable_request() {
  
  if (request_ == nullptr) {
    auto* p = CreateMaybeMessage<::lcy::rpc::Request>(GetArena());
    request_ = p;
  }
  return request_;
}
inline ::lcy::rpc::Request* Message::mutable_request() {
  // @@protoc_insertion_point(field_mutable:lcy.rpc.Message.request)
  return _internal_mutable_request();
}
inline void Message::set_allocated_request(::lcy::rpc::Request* request) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete request_;
  }
  if (request) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(request);
    if (message_arena != submessage_arena) {
      request = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, request, submessage_arena);
    }
    
  } else {
    
  }
  request_ = request;
  // @@protoc_insertion_point(field_set_allocated:lcy.rpc.Message.request)
}

// .lcy.rpc.Response response = 4;
inline bool Message::_internal_has_response() const {
  return this != internal_default_instance() && response_ != nullptr;
}
inline bool Message::has_response() const {
  return _internal_has_response();
}
inline void Message::clear_response() {
  if (GetArena() == nullptr && response_ != nullptr) {
    delete response_;
  }
  response_ = nullptr;
}
inline const ::lcy::rpc::Response& Message::_internal_response() const {
  const ::lcy::rpc::Response* p = response_;
  return p != nullptr ? *p : *reinterpret_cast<const ::lcy::rpc::Response*>(
      &::lcy::rpc::_Response_default_instance_);
}
inline const ::lcy::rpc::Response& Message::response() const {
  // @@protoc_insertion_point(field_get:lcy.rpc.Message.response)
  return _internal_response();
}
inline void Message::unsafe_arena_set_allocated_response(
    ::lcy::rpc::Response* response) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(response_);
  }
  response_ = response;
  if (response) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:lcy.rpc.Message.response)
}
inline ::lcy::rpc::Response* Message::release_response() {
  
  ::lcy::rpc::Response* temp = response_;
  response_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::lcy::rpc::Response* Message::unsafe_arena_release_response() {
  // @@protoc_insertion_point(field_release:lcy.rpc.Message.response)
  
  ::lcy::rpc::Response* temp = response_;
  response_ = nullptr;
  return temp;
}
inline ::lcy::rpc::Response* Message::_internal_mutable_response() {
  
  if (response_ == nullptr) {
    auto* p = CreateMaybeMessage<::lcy::rpc::Response>(GetArena());
    response_ = p;
  }
  return response_;
}
inline ::lcy::rpc::Response* Message::mutable_response() {
  // @@protoc_insertion_point(field_mutable:lcy.rpc.Message.response)
  return _internal_mutable_response();
}
inline void Message::set_allocated_response(::lcy::rpc::Response* response) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete response_;
  }
  if (response) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(response);
    if (message_arena != submessage_arena) {
      response = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, response, submessage_arena);
    }
    
  } else {
    
  }
  response_ = response;
  // @@protoc_insertion_point(field_set_allocated:lcy.rpc.Message.response)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace rpc
}  // namespace lcy

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::lcy::rpc::type> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::lcy::rpc::type>() {
  return ::lcy::rpc::type_descriptor();
}
template <> struct is_proto_enum< ::lcy::rpc::err> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::lcy::rpc::err>() {
  return ::lcy::rpc::err_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_rpc_2eproto
